import PDFDocument from "pdfkit";

export const createPolicyPdf = (policy) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).text("Car Insurance Policy Certificate", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Policy Number: ${policy.policyNumber}`);
    doc.text(`Customer: ${policy.customer?.fullName || "N/A"}`);
    doc.text(`Vehicle: ${policy.vehicle?.make || ""} ${policy.vehicle?.model || ""}`);
    doc.text(`Registration: ${policy.vehicle?.registrationNumber || "N/A"}`);
    doc.text(`Policy Type: ${policy.type}`);
    doc.text(`Coverage Amount: ${policy.coverageAmount}`);
    doc.text(`Premium Amount: ${policy.premiumAmount}`);
    doc.text(`Start Date: ${new Date(policy.startDate).toLocaleDateString()}`);
    doc.text(`End Date: ${new Date(policy.endDate).toLocaleDateString()}`);
    doc.text(`Status: ${policy.status}`);
    doc.moveDown();
    doc.text("This certificate was generated by the Car Insurance Company Management System.");

    doc.end();
  });
