import PDFDocument from "pdfkit";

export const createSecurityReportPdf = ({ summary, events, generatedBy }) =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).text("Cyber Security Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: "center" });
    doc.text(`Generated by: ${generatedBy?.name || "Admin"}`, { align: "center" });
    doc.moveDown();

    doc.fontSize(14).text("7-Day Security Summary");
    doc.moveDown(0.5);
    doc.fontSize(11);
    doc.text(`Total Security Events: ${summary.totalEvents}`);
    doc.text(`Failed Logins: ${summary.failedLogins}`);
    doc.text(`Successful Logins: ${summary.successfulLogins}`);
    doc.text(`Locked Accounts: ${summary.lockedAccounts}`);
    doc.text(`High/Critical Events: ${summary.criticalEvents}`);
    doc.moveDown();

    doc.fontSize(14).text("Top Source IPs");
    doc.moveDown(0.5);
    if (summary.topIps.length) {
      summary.topIps.forEach((ip) => {
        doc.fontSize(10).text(`${ip._id}: ${ip.count} events, ${ip.failed} failed login(s)`);
      });
    } else {
      doc.fontSize(10).text("No IP activity captured.");
    }
    doc.moveDown();

    doc.fontSize(14).text("Recent Security Events");
    doc.moveDown(0.5);
    events.forEach((event) => {
      doc
        .fontSize(10)
        .text(`${new Date(event.createdAt).toLocaleString()} | ${event.severity.toUpperCase()} | ${event.type}`)
        .text(`Email: ${event.email || event.user?.email || "N/A"} | IP: ${event.ipAddress || "N/A"}`)
        .text(event.message)
        .moveDown(0.5);
    });

    doc.end();
  });
